# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: testing-ssh Node.js CI

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.2.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - run: az login -u ${{secrets.AZUREUSERNAME}} -p ${{secrets.AZUREPASS}}
    - run: az acr login --name aryanregistry
    
    
    - name: Build, tag, and push image to Azure CR
      env:
        ACR_REGISTRY: aryanregistry
        ACR_REPOSITORY: azurecr.io
        IMAGE_TAG: nodejs_demo_image
      run: |
        docker build -t $ACR_REGISTRY.$ACR_REPOSITORY/images/$IMAGE_TAG:latest .
        docker push $ACR_REGISTRY.$ACR_REPOSITORY/images/$IMAGE_TAG:latest
    
    
    
    
   
    - name: SSH Remote Commands
      uses: fifsky/ssh-action@master
      with:
        key: ${{secrets.SERVER_KEY}}
        host: ${{secrets.SERVER_IP}}
        user: ${{secrets.SERVER_USERNAME}}
        command: |
           sudo docker pull $ACR_REGISTRY/$ACR_REPOSITORY/images/$IMAGE_TAG:latest
           sudo docker run -d -p 1234:3000 $ACR_REGISTRY/$ACR_REPOSITORY/images/$IMAGE_TAG:latest
          
