# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: testing-ssh Node.js CI

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.2.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    
   
    - name: SSH Remote Commands
      uses: fifsky/ssh-action@master
      with:
        key: ${{secrets.SERVER_KEY}}
        host: ${{secrets.SERVER_IP}}
        user: ${{secrets.SERVER_USERNAME}}
        command: |
          cd React-Gym-Website
          git remote add origin https://github.com/AryanSemwal/React-Gym-Website.git
          git pull origin master
          ls
        
